// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `CredentialTarget`

Future<List<FileStatus>> getStatus({required String path}) =>
    RustLib.instance.api.crateApiGitGetStatus(path: path);

Future<List<BranchInfo>> getBranches({required String path}) =>
    RustLib.instance.api.crateApiGitGetBranches(path: path);

Future<void> checkoutBranch({required String path, required String name}) =>
    RustLib.instance.api.crateApiGitCheckoutBranch(path: path, name: name);

Future<void> createBranch(
        {required String path,
        required String name,
        required bool checkout,
        String? base}) =>
    RustLib.instance.api.crateApiGitCreateBranch(
        path: path, name: name, checkout: checkout, base: base);

Future<void> deleteBranch({required String path, required String name}) =>
    RustLib.instance.api.crateApiGitDeleteBranch(path: path, name: name);

Future<void> renameBranch(
        {required String path,
        required String name,
        required String newName}) =>
    RustLib.instance.api
        .crateApiGitRenameBranch(path: path, name: name, newName: newName);

Future<Tracking> getBranchTracking({required String path}) =>
    RustLib.instance.api.crateApiGitGetBranchTracking(path: path);

Future<List<String>> getRemoteBranches({required String path}) =>
    RustLib.instance.api.crateApiGitGetRemoteBranches(path: path);

Future<List<String>> getTags({required String path}) =>
    RustLib.instance.api.crateApiGitGetTags(path: path);

Future<String> createTag(
        {required String path,
        required String name,
        required String message,
        String? oid}) =>
    RustLib.instance.api.crateApiGitCreateTag(
        path: path, name: name, message: message, oid: oid);

Future<String> deleteTag({required String path, required String name}) =>
    RustLib.instance.api.crateApiGitDeleteTag(path: path, name: name);

Future<String> pushTag({required String path, required String name}) =>
    RustLib.instance.api.crateApiGitPushTag(path: path, name: name);

Future<List<RemoteInfo>> getRemotes({required String path}) =>
    RustLib.instance.api.crateApiGitGetRemotes(path: path);

Future<String> addRemote(
        {required String path, required String name, required String url}) =>
    RustLib.instance.api.crateApiGitAddRemote(path: path, name: name, url: url);

Future<String> removeRemote({required String path, required String name}) =>
    RustLib.instance.api.crateApiGitRemoveRemote(path: path, name: name);

Future<String> deleteRemoteBranch(
        {required String path,
        required String remote,
        required String branch}) =>
    RustLib.instance.api.crateApiGitDeleteRemoteBranch(
        path: path, remote: remote, branch: branch);

Future<String> checkoutRef({required String path, required String refName}) =>
    RustLib.instance.api.crateApiGitCheckoutRef(path: path, refName: refName);

Future<List<String>> getCommitMessages(
        {required String path, required BigInt limit}) =>
    RustLib.instance.api.crateApiGitGetCommitMessages(path: path, limit: limit);

Future<List<CommitInfo>> searchCommits(
        {required String path,
        required String query,
        required String author,
        required BigInt limit}) =>
    RustLib.instance.api.crateApiGitSearchCommits(
        path: path, query: query, author: author, limit: limit);

Future<List<CommitInfo>> getFileHistory(
        {required String path, required String file, required BigInt limit}) =>
    RustLib.instance.api
        .crateApiGitGetFileHistory(path: path, file: file, limit: limit);

Future<List<BlameLine>> getBlame(
        {required String path, required String file}) =>
    RustLib.instance.api.crateApiGitGetBlame(path: path, file: file);

Future<List<GraphCommit>> getGraph(
        {required String path, required BigInt limit}) =>
    RustLib.instance.api.crateApiGitGetGraph(path: path, limit: limit);

Future<void> stageFile({required String path, required String file}) =>
    RustLib.instance.api.crateApiGitStageFile(path: path, file: file);

Future<void> unstageFile({required String path, required String file}) =>
    RustLib.instance.api.crateApiGitUnstageFile(path: path, file: file);

Future<String> stageAll({required String path, required List<String> files}) =>
    RustLib.instance.api.crateApiGitStageAll(path: path, files: files);

Future<String> unstageAll(
        {required String path, required List<String> files}) =>
    RustLib.instance.api.crateApiGitUnstageAll(path: path, files: files);

Future<String> commit(
        {required String path,
        required String message,
        required bool amend,
        String? author,
        required bool signoff}) =>
    RustLib.instance.api.crateApiGitCommit(
        path: path,
        message: message,
        amend: amend,
        author: author,
        signoff: signoff);

Future<String> getHeadMessage({required String path}) =>
    RustLib.instance.api.crateApiGitGetHeadMessage(path: path);

Future<String> getUnstagedDiff({required String path, required String file}) =>
    RustLib.instance.api.crateApiGitGetUnstagedDiff(path: path, file: file);

Future<String> getStagedDiff({required String path, required String file}) =>
    RustLib.instance.api.crateApiGitGetStagedDiff(path: path, file: file);

Future<void> discardChanges({required String path, required String file}) =>
    RustLib.instance.api.crateApiGitDiscardChanges(path: path, file: file);

Future<List<FileStatus>> getCommitFiles(
        {required String path, required String oid}) =>
    RustLib.instance.api.crateApiGitGetCommitFiles(path: path, oid: oid);

Future<List<FileStatus>> getPushFiles({required String path}) =>
    RustLib.instance.api.crateApiGitGetPushFiles(path: path);

Future<String> getCommitDiff(
        {required String path, required String oid, required String file}) =>
    RustLib.instance.api
        .crateApiGitGetCommitDiff(path: path, oid: oid, file: file);

Future<Hunks> getHunks(
        {required String path, required String file, required bool staged}) =>
    RustLib.instance.api
        .crateApiGitGetHunks(path: path, file: file, staged: staged);

Future<void> applyHunk(
        {required String path, required String patch, required bool reverse}) =>
    RustLib.instance.api
        .crateApiGitApplyHunk(path: path, patch: patch, reverse: reverse);

Future<String> stashSave({required String path, required String message}) =>
    RustLib.instance.api.crateApiGitStashSave(path: path, message: message);

Future<List<StashEntry>> stashList({required String path}) =>
    RustLib.instance.api.crateApiGitStashList(path: path);

Future<String> stashPop({required String path, required BigInt index}) =>
    RustLib.instance.api.crateApiGitStashPop(path: path, index: index);

Future<String> stashDrop({required String path, required BigInt index}) =>
    RustLib.instance.api.crateApiGitStashDrop(path: path, index: index);

Future<String> resetTo(
        {required String path, required String oid, required String mode}) =>
    RustLib.instance.api.crateApiGitResetTo(path: path, oid: oid, mode: mode);

Future<String> revertCommit({required String path, required String oid}) =>
    RustLib.instance.api.crateApiGitRevertCommit(path: path, oid: oid);

Future<String> cherryPick({required String path, required String oid}) =>
    RustLib.instance.api.crateApiGitCherryPick(path: path, oid: oid);

Future<String> mergeBranch({required String path, required String name}) =>
    RustLib.instance.api.crateApiGitMergeBranch(path: path, name: name);

Future<String> getRepoState({required String path}) =>
    RustLib.instance.api.crateApiGitGetRepoState(path: path);

Future<String> opAction(
        {required String path, required String op, required String action}) =>
    RustLib.instance.api
        .crateApiGitOpAction(path: path, op: op, action: action);

Future<List<String>> getConflicts({required String path}) =>
    RustLib.instance.api.crateApiGitGetConflicts(path: path);

Future<String> setConflictStyle(
        {required String path, required String file, required String style}) =>
    RustLib.instance.api
        .crateApiGitSetConflictStyle(path: path, file: file, style: style);

Future<void> resolveConflict(
        {required String path, required String file, required String side}) =>
    RustLib.instance.api
        .crateApiGitResolveConflict(path: path, file: file, side: side);

Future<void> resolveWithContent(
        {required String path,
        required String file,
        required String content}) =>
    RustLib.instance.api.crateApiGitResolveWithContent(
        path: path, file: file, content: content);

Future<String> readWorktreeFile({required String path, required String file}) =>
    RustLib.instance.api.crateApiGitReadWorktreeFile(path: path, file: file);

Future<void> openInEditor(
        {required String path, required String file, required String editor}) =>
    RustLib.instance.api
        .crateApiGitOpenInEditor(path: path, file: file, editor: editor);

Future<void> openProjectWithFile(
        {required String project,
        required String path,
        required String file,
        required String editor}) =>
    RustLib.instance.api.crateApiGitOpenProjectWithFile(
        project: project, path: path, file: file, editor: editor);

Future<void> openPath({required String path, required String editor}) =>
    RustLib.instance.api.crateApiGitOpenPath(path: path, editor: editor);

Future<List<String>> listEditors() =>
    RustLib.instance.api.crateApiGitListEditors();

Future<Uint8List> editorIcon({required String name}) =>
    RustLib.instance.api.crateApiGitEditorIcon(name: name);

Future<String> createPatch({required String path}) =>
    RustLib.instance.api.crateApiGitCreatePatch(path: path);

Future<String> createCommitPatch({required String path, required String oid}) =>
    RustLib.instance.api.crateApiGitCreateCommitPatch(path: path, oid: oid);

Future<void> writeClipboard({required String text}) =>
    RustLib.instance.api.crateApiGitWriteClipboard(text: text);

Future<void> savePatch({required String file, required String content}) =>
    RustLib.instance.api.crateApiGitSavePatch(file: file, content: content);

Future<String> readPatchFile({required String file}) =>
    RustLib.instance.api.crateApiGitReadPatchFile(file: file);

Future<void> applyPatch({required String path, required String patch}) =>
    RustLib.instance.api.crateApiGitApplyPatch(path: path, patch: patch);

Future<String> readClipboard() =>
    RustLib.instance.api.crateApiGitReadClipboard();

Future<List<TodoCommit>> getRebaseTodo(
        {required String path, required String base}) =>
    RustLib.instance.api.crateApiGitGetRebaseTodo(path: path, base: base);

Future<String> rebaseInteractive(
        {required String path,
        required String base,
        required String todo,
        required List<String> messages,
        required bool autostash}) =>
    RustLib.instance.api.crateApiGitRebaseInteractive(
        path: path,
        base: base,
        todo: todo,
        messages: messages,
        autostash: autostash);

Future<GitCredentialInfo> getGitCredential({required String path}) =>
    RustLib.instance.api.crateApiGitGetGitCredential(path: path);

Future<GitCredentialInfo> saveGitCredential(
        {required String path,
        required String username,
        required String token}) =>
    RustLib.instance.api.crateApiGitSaveGitCredential(
        path: path, username: username, token: token);

Future<String> testGitCredential({required String path}) =>
    RustLib.instance.api.crateApiGitTestGitCredential(path: path);

Future<Identity> getIdentity({required String path}) =>
    RustLib.instance.api.crateApiGitGetIdentity(path: path);

Future<bool?> getPullRebase({required String path}) =>
    RustLib.instance.api.crateApiGitGetPullRebase(path: path);

Future<void> setIdentity(
        {required String path,
        required String name,
        required String email,
        required bool global}) =>
    RustLib.instance.api.crateApiGitSetIdentity(
        path: path, name: name, email: email, global: global);

Future<String> aiChat(
        {required String url,
        required String token,
        required String model,
        required String system,
        required String user}) =>
    RustLib.instance.api.crateApiGitAiChat(
        url: url, token: token, model: model, system: system, user: user);

Future<String> gitFetch({required String path}) =>
    RustLib.instance.api.crateApiGitGitFetch(path: path);

Future<String> gitPull({required String path, String? strategy}) =>
    RustLib.instance.api.crateApiGitGitPull(path: path, strategy: strategy);

Future<String> gitPush({required String path}) =>
    RustLib.instance.api.crateApiGitGitPush(path: path);

Future<String> updateBranch({required String path, required String name}) =>
    RustLib.instance.api.crateApiGitUpdateBranch(path: path, name: name);

Future<String> pushBranch({required String path, required String name}) =>
    RustLib.instance.api.crateApiGitPushBranch(path: path, name: name);

Future<String> gitPushForce({required String path}) =>
    RustLib.instance.api.crateApiGitGitPushForce(path: path);

class BlameLine {
  final String oid;
  final String author;
  final String summary;
  final String content;

  const BlameLine({
    required this.oid,
    required this.author,
    required this.summary,
    required this.content,
  });

  @override
  int get hashCode =>
      oid.hashCode ^ author.hashCode ^ summary.hashCode ^ content.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BlameLine &&
          runtimeType == other.runtimeType &&
          oid == other.oid &&
          author == other.author &&
          summary == other.summary &&
          content == other.content;
}

class BranchInfo {
  final String name;
  final bool isCurrent;

  const BranchInfo({
    required this.name,
    required this.isCurrent,
  });

  @override
  int get hashCode => name.hashCode ^ isCurrent.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BranchInfo &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          isCurrent == other.isCurrent;
}

class CommitInfo {
  final String id;
  final String summary;
  final String author;
  final PlatformInt64 time;

  const CommitInfo({
    required this.id,
    required this.summary,
    required this.author,
    required this.time,
  });

  @override
  int get hashCode =>
      id.hashCode ^ summary.hashCode ^ author.hashCode ^ time.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CommitInfo &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          summary == other.summary &&
          author == other.author &&
          time == other.time;
}

class FileStatus {
  final String path;
  final String status;
  final bool staged;

  const FileStatus({
    required this.path,
    required this.status,
    required this.staged,
  });

  @override
  int get hashCode => path.hashCode ^ status.hashCode ^ staged.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FileStatus &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          status == other.status &&
          staged == other.staged;
}

class GitCredentialInfo {
  final String remote;
  final String transport;
  final String host;
  final String repository;
  final String username;
  final String helper;
  final bool hasCredential;

  const GitCredentialInfo({
    required this.remote,
    required this.transport,
    required this.host,
    required this.repository,
    required this.username,
    required this.helper,
    required this.hasCredential,
  });

  @override
  int get hashCode =>
      remote.hashCode ^
      transport.hashCode ^
      host.hashCode ^
      repository.hashCode ^
      username.hashCode ^
      helper.hashCode ^
      hasCredential.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GitCredentialInfo &&
          runtimeType == other.runtimeType &&
          remote == other.remote &&
          transport == other.transport &&
          host == other.host &&
          repository == other.repository &&
          username == other.username &&
          helper == other.helper &&
          hasCredential == other.hasCredential;
}

class GraphCommit {
  final String id;
  final String summary;
  final String author;
  final PlatformInt64 time;
  final List<String> parents;
  final List<String> refs;

  const GraphCommit({
    required this.id,
    required this.summary,
    required this.author,
    required this.time,
    required this.parents,
    required this.refs,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      summary.hashCode ^
      author.hashCode ^
      time.hashCode ^
      parents.hashCode ^
      refs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GraphCommit &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          summary == other.summary &&
          author == other.author &&
          time == other.time &&
          parents == other.parents &&
          refs == other.refs;
}

class Hunks {
  final String header;
  final List<String> hunks;

  const Hunks({
    required this.header,
    required this.hunks,
  });

  @override
  int get hashCode => header.hashCode ^ hunks.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Hunks &&
          runtimeType == other.runtimeType &&
          header == other.header &&
          hunks == other.hunks;
}

class Identity {
  final String name;
  final String email;

  const Identity({
    required this.name,
    required this.email,
  });

  @override
  int get hashCode => name.hashCode ^ email.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Identity &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          email == other.email;
}

class RemoteInfo {
  final String name;
  final String url;

  const RemoteInfo({
    required this.name,
    required this.url,
  });

  @override
  int get hashCode => name.hashCode ^ url.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RemoteInfo &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          url == other.url;
}

class RepoRef {
  final String path;
  final String name;
  final String branch;

  const RepoRef({
    required this.path,
    required this.name,
    required this.branch,
  });

  @override
  int get hashCode => path.hashCode ^ name.hashCode ^ branch.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RepoRef &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          name == other.name &&
          branch == other.branch;
}

class StashEntry {
  final BigInt index;
  final String message;

  const StashEntry({
    required this.index,
    required this.message,
  });

  @override
  int get hashCode => index.hashCode ^ message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StashEntry &&
          runtimeType == other.runtimeType &&
          index == other.index &&
          message == other.message;
}

class TodoCommit {
  final String oid;
  final String summary;

  const TodoCommit({
    required this.oid,
    required this.summary,
  });

  @override
  int get hashCode => oid.hashCode ^ summary.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TodoCommit &&
          runtimeType == other.runtimeType &&
          oid == other.oid &&
          summary == other.summary;
}

class Tracking {
  final String? branch;
  final String? upstream;
  final BigInt ahead;
  final BigInt behind;

  const Tracking({
    this.branch,
    this.upstream,
    required this.ahead,
    required this.behind,
  });

  @override
  int get hashCode =>
      branch.hashCode ^ upstream.hashCode ^ ahead.hashCode ^ behind.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Tracking &&
          runtimeType == other.runtimeType &&
          branch == other.branch &&
          upstream == other.upstream &&
          ahead == other.ahead &&
          behind == other.behind;
}

class Workspace {
  final String root;
  final List<RepoRef> repos;

  const Workspace({
    required this.root,
    required this.repos,
  });

  @override
  int get hashCode => root.hashCode ^ repos.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Workspace &&
          runtimeType == other.runtimeType &&
          root == other.root &&
          repos == other.repos;
}
