// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'git.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `watch_state`

/// Open a workspace. This does not start watching —
/// core keeps the two apart, and Dart calls [`watch_repo`] with the resolved
/// root when it wants change notifications.
Future<Workspace> openWorkspace({required String path}) =>
    RustLib.instance.api.crateApiWatchOpenWorkspace(path: path);

/// Watch `path` and push "refs" or "worktree" into the stream on every
/// debounced burst. "refs" means HEAD or a ref moved, so branch labels and the
/// graph are stale too; "worktree" means only file contents changed.
///
/// The sink is moved into core's callback and lives as long as the watcher.
Stream<String> watchRepo({required String path}) =>
    RustLib.instance.api.crateApiWatchWatchRepo(path: path);

/// Clone into `dir`, streaming git's progress lines, and return the path of the
/// created working copy.
Stream<String> cloneRepo({required String url, required String dir}) =>
    RustLib.instance.api.crateApiWatchCloneRepo(url: url, dir: dir);
