// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/git.dart';
import 'api/watch.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  RustStreamSink<String> dco_decode_StreamSink_String_Sse(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  BlameLine dco_decode_blame_line(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  bool dco_decode_box_autoadd_bool(dynamic raw);

  @protected
  BranchInfo dco_decode_branch_info(dynamic raw);

  @protected
  CommitInfo dco_decode_commit_info(dynamic raw);

  @protected
  FileStatus dco_decode_file_status(dynamic raw);

  @protected
  GitCredentialInfo dco_decode_git_credential_info(dynamic raw);

  @protected
  GraphCommit dco_decode_graph_commit(dynamic raw);

  @protected
  Hunks dco_decode_hunks(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  Identity dco_decode_identity(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<BlameLine> dco_decode_list_blame_line(dynamic raw);

  @protected
  List<BranchInfo> dco_decode_list_branch_info(dynamic raw);

  @protected
  List<CommitInfo> dco_decode_list_commit_info(dynamic raw);

  @protected
  List<FileStatus> dco_decode_list_file_status(dynamic raw);

  @protected
  List<GraphCommit> dco_decode_list_graph_commit(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<RemoteInfo> dco_decode_list_remote_info(dynamic raw);

  @protected
  List<RepoRef> dco_decode_list_repo_ref(dynamic raw);

  @protected
  List<StashEntry> dco_decode_list_stash_entry(dynamic raw);

  @protected
  List<TodoCommit> dco_decode_list_todo_commit(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  bool? dco_decode_opt_box_autoadd_bool(dynamic raw);

  @protected
  RemoteInfo dco_decode_remote_info(dynamic raw);

  @protected
  RepoRef dco_decode_repo_ref(dynamic raw);

  @protected
  StashEntry dco_decode_stash_entry(dynamic raw);

  @protected
  TodoCommit dco_decode_todo_commit(dynamic raw);

  @protected
  Tracking dco_decode_tracking(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  Workspace dco_decode_workspace(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  RustStreamSink<String> sse_decode_StreamSink_String_Sse(
      SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  BlameLine sse_decode_blame_line(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  bool sse_decode_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  BranchInfo sse_decode_branch_info(SseDeserializer deserializer);

  @protected
  CommitInfo sse_decode_commit_info(SseDeserializer deserializer);

  @protected
  FileStatus sse_decode_file_status(SseDeserializer deserializer);

  @protected
  GitCredentialInfo sse_decode_git_credential_info(
      SseDeserializer deserializer);

  @protected
  GraphCommit sse_decode_graph_commit(SseDeserializer deserializer);

  @protected
  Hunks sse_decode_hunks(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  Identity sse_decode_identity(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<BlameLine> sse_decode_list_blame_line(SseDeserializer deserializer);

  @protected
  List<BranchInfo> sse_decode_list_branch_info(SseDeserializer deserializer);

  @protected
  List<CommitInfo> sse_decode_list_commit_info(SseDeserializer deserializer);

  @protected
  List<FileStatus> sse_decode_list_file_status(SseDeserializer deserializer);

  @protected
  List<GraphCommit> sse_decode_list_graph_commit(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<RemoteInfo> sse_decode_list_remote_info(SseDeserializer deserializer);

  @protected
  List<RepoRef> sse_decode_list_repo_ref(SseDeserializer deserializer);

  @protected
  List<StashEntry> sse_decode_list_stash_entry(SseDeserializer deserializer);

  @protected
  List<TodoCommit> sse_decode_list_todo_commit(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  bool? sse_decode_opt_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  RemoteInfo sse_decode_remote_info(SseDeserializer deserializer);

  @protected
  RepoRef sse_decode_repo_ref(SseDeserializer deserializer);

  @protected
  StashEntry sse_decode_stash_entry(SseDeserializer deserializer);

  @protected
  TodoCommit sse_decode_todo_commit(SseDeserializer deserializer);

  @protected
  Tracking sse_decode_tracking(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  Workspace sse_decode_workspace(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
      AnyhowException self, SseSerializer serializer);

  @protected
  void sse_encode_StreamSink_String_Sse(
      RustStreamSink<String> self, SseSerializer serializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_blame_line(BlameLine self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_branch_info(BranchInfo self, SseSerializer serializer);

  @protected
  void sse_encode_commit_info(CommitInfo self, SseSerializer serializer);

  @protected
  void sse_encode_file_status(FileStatus self, SseSerializer serializer);

  @protected
  void sse_encode_git_credential_info(
      GitCredentialInfo self, SseSerializer serializer);

  @protected
  void sse_encode_graph_commit(GraphCommit self, SseSerializer serializer);

  @protected
  void sse_encode_hunks(Hunks self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_identity(Identity self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_blame_line(
      List<BlameLine> self, SseSerializer serializer);

  @protected
  void sse_encode_list_branch_info(
      List<BranchInfo> self, SseSerializer serializer);

  @protected
  void sse_encode_list_commit_info(
      List<CommitInfo> self, SseSerializer serializer);

  @protected
  void sse_encode_list_file_status(
      List<FileStatus> self, SseSerializer serializer);

  @protected
  void sse_encode_list_graph_commit(
      List<GraphCommit> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer);

  @protected
  void sse_encode_list_remote_info(
      List<RemoteInfo> self, SseSerializer serializer);

  @protected
  void sse_encode_list_repo_ref(List<RepoRef> self, SseSerializer serializer);

  @protected
  void sse_encode_list_stash_entry(
      List<StashEntry> self, SseSerializer serializer);

  @protected
  void sse_encode_list_todo_commit(
      List<TodoCommit> self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_bool(bool? self, SseSerializer serializer);

  @protected
  void sse_encode_remote_info(RemoteInfo self, SseSerializer serializer);

  @protected
  void sse_encode_repo_ref(RepoRef self, SseSerializer serializer);

  @protected
  void sse_encode_stash_entry(StashEntry self, SseSerializer serializer);

  @protected
  void sse_encode_todo_commit(TodoCommit self, SseSerializer serializer);

  @protected
  void sse_encode_tracking(Tracking self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_workspace(Workspace self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
